# install neccessary packages
- name: Update OS
  become: true
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Ensure neccessary packages are installed.
  ansible.builtin.apt:
    pkg:
      - stow
      - zsh
      - zsh-syntax-highlighting
      - wget
      - curl
      - nginx
      - php8.2
      - php8.2-cli
      - php8.2-bz2
      - php8.2-mbstring
      - php8.2-intl
      - certbot
      - htop
      - docker
      - python3
    state: present

- name: Add new user
  ansible.builtin.user:
    name: "{{ os_user }}"
    shell: /bin/zsh
    create_home: true
    generate_ssh_key: yes
    password: "{{ 'password' | password_hash('sha512') }}"
    update_password: on_create
    ssh_key_file: .ssh/id_rsa
    ssh_key_bits: 4096
    expires: -1

- name: Ensure dotfiles repository is cloned to {{ item }} home directory.
  ansible.builtin.git:
    repo: "https://{{ github_user }}:{{ github_token }}@github.com/{{ github_user }}/vps-dotfiles.git"
    dest: "/home/{{ item }}/.dotfiles"
    version: main
    force: true
  loop:
    - "{{ os_user }}"
    - "root"

- name: Recursively change ownership of .dotfiles
  ansible.builtin.file:
    path: "/home/{{ os_user }}/.dotfiles"
    state: directory
    recurse: yes
    owner: "{{ os_user }}"
    group: "{{ os_user }}"

- name: Ensure login shell of {{ item }} is set to `/bin/zsh`.
  ansible.builtin.command: usermod --shell /usr/bin/zsh {{ item }}
  become: true
  changed_when: false
  loop:
    - "{{ os_user }}"
    - "root"

- name: Ensure home directory is cleaned up
  ansible.builtin.file:
    path: "/home/{{ item[0] }}/{{ item[1] }}"
    state: absent
  with_nested:
    - [ 'root', '{{ os_user }}' ]
    - [ '.bashrc', '.bash_logout', '.dotfiles/.git' ]

- name: Ensure .dotfiles symlinks are set
  ansible.builtin.shell:
    cmd: stow *
    args:
      chdir: "/home/{{ item }}/.dotfiles"
  loop:
    - "{{ os_user }}"
    - "root"